-- Triggers para cada tabla
CREATE OR REPLACE TRIGGER TRG_CLIENTES
BEFORE INSERT ON clientes
FOR EACH ROW
BEGIN 
    SELECT SEQ_CLIENTES.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_DIRECCIONES_CLIENTE
BEFORE INSERT ON direcciones_cliente
FOR EACH ROW
BEGIN 
    SELECT SEQ_DIRECCIONES_CLIENTE.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_CELULARES_CLIENTE
BEFORE INSERT ON celulares_cliente
FOR EACH ROW
BEGIN 
    SELECT SEQ_CELULARES_CLIENTE.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_CONSUMIDORES
BEFORE INSERT ON consumidores
FOR EACH ROW
BEGIN 
    SELECT SEQ_CONSUMIDORES.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_EMPRESAS
BEFORE INSERT ON empresas
FOR EACH ROW
BEGIN 
    SELECT SEQ_EMPRESAS.NEXTVAL INTO :NEW.nit FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_AUDITORIAS
BEFORE INSERT ON auditorias
FOR EACH ROW
BEGIN 
    SELECT SEQ_AUDITORIAS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_DONACIONES
BEFORE INSERT ON donaciones
FOR EACH ROW
BEGIN 
    SELECT SEQ_DONACIONES.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_CARRITOS_COMPRAS
BEFORE INSERT ON carritoscompras
FOR EACH ROW
BEGIN 
    SELECT SEQ_CARRITOS_COMPRAS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_LISTA_PRODUCTOS
BEFORE INSERT ON listaproductos
FOR EACH ROW
BEGIN 
    SELECT SEQ_LISTA_PRODUCTOS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_MENUS_ALEATORIOS
BEFORE INSERT ON menusaleatorios
FOR EACH ROW
BEGIN 
    SELECT SEQ_MENUS_ALEATORIOS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_PLATOS
BEFORE INSERT ON platos
FOR EACH ROW
BEGIN 
    SELECT SEQ_PLATOS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_PEDIDOS
BEFORE INSERT ON pedidos
FOR EACH ROW
BEGIN 
    SELECT SEQ_PEDIDOS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_CALIFICACIONES
BEFORE INSERT ON calificaciones
FOR EACH ROW
BEGIN 
    SELECT SEQ_CALIFICACIONES.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_FACTURAS
BEFORE INSERT ON facturas
FOR EACH ROW
BEGIN 
    SELECT SEQ_FACTURAS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_ENVIOS
BEFORE INSERT ON envios
FOR EACH ROW
BEGIN 
    SELECT SEQ_ENVIOS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_BONOS
BEFORE INSERT ON bonos
FOR EACH ROW
BEGIN 
    SELECT SEQ_BONOS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_DESCRIPCIONES_BONO
BEFORE INSERT ON descripciones_bono
FOR EACH ROW
BEGIN 
    SELECT SEQ_DESCRIPCIONES_BONO.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_DOMICILIARIOS
BEFORE INSERT ON domiciliarios
FOR EACH ROW
BEGIN 
    SELECT SEQ_DOMICILIARIOS.NEXTVAL INTO :NEW.id FROM dual;
END;

CREATE OR REPLACE TRIGGER TRG_PLATOS_EMPRESAS
BEFORE INSERT ON platos_empresas
FOR EACH ROW
BEGIN 
    SELECT SEQ_PLATOS_EMPRESAS.NEXTVAL INTO :NEW.id FROM dual;
END;