-- Script para crear secuencias y triggers para las tablas de la base de datos
CREATE SEQUENCE SEQ_CLIENTES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_DIRECCIONES_CLIENTE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_CELULARES_CLIENTE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_CONSUMIDORES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_EMPRESAS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_AUDITORIAS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_DONACIONES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_CARRITOS_COMPRAS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_LISTA_PRODUCTOS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_MENUS_ALEATORIOS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLATOS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_PEDIDOS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_CALIFICACIONES
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_FACTURAS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_ENVIOS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_BONOS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_DESCRIPCIONES_BONO
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_DOMICILIARIOS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEQ_PLATOS_EMPRESAS
START WITH 1
INCREMENT BY 1;



