CREATE TABLE clientes (
    id CHAR(10) NOT NULL,
    correo VARCHAR2(50)
    );
    
CREATE TABLE direcciones_Cliente (
    id CHAR(10) NOT NULL,
    idCliente CHAR(10) NOT NULL,
    direccionCliente VARCHAR(50) NOT NULL
    );
    
CREATE TABLE celulares_Cliente (
    id CHAR(10) NOT NULL,
    idCliente CHAR(10) NOT NULL,
    celularCliente NUMBER(20) NOT NULL
    );
    
CREATE TABLE consumidores (
    id CHAR(10) NOT NULL,
    nombre CHAR(100) NOT NULL, 
    preferencia_Alimento VARCHAR2(100) 
    );
    
CREATE TABLE empresas (
    nit CHAR(10) NOT NULL,
    nombre CHAR(100) NOT NULL,
    tipoNegocio VARCHAR2(3) NOT NULL
    );  
    
CREATE TABLE auditorias_delizia (
    id VARCHAR2(10) NOT NULL,
    nitEmpresa CHAR(10) NOT NULL,
    platos_vendidos NUMBER NOT NULL, 
    platos_por_vender NUMBER(8) NOT NULL,
    ganancias NUMBER(8) NOT NULL,
    perdidas NUMBER(8) NOT NULL,
    fecha_auditoria DATE NOT NULL
    );

CREATE TABLE donaciones (
    id VARCHAR2(10) NOT NULL,
    fecha DATE NOT NULL,
    cantidad NUMBER NULL,
    tipo VARCHAR(1) NOT NULL,
    nit_empresa CHAR(10) NOT NULL
    );

CREATE TABLE carritosCompras (
    id VARCHAR(10) NOT NULL,    
    idConsumidor CHAR(10) NOT NULL    
    );


CREATE TABLE menusAleatorios (
    id VARCHAR2(10) NOT NULL,
    nitEmpresa CHAR(10) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    precio NUMBER(8) NOT NULL,
    nombre VARCHAR2(50) NOT NULL
    );
        
CREATE TABLE platos (
    id VARCHAR(10) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    precio NUMBER(8) NOT NULL,
    nit_empresa CHAR(10) NOT NULL
    );

CREATE TABLE menus_platos (
    idMenuAleatorio VARCHAR2(10) NOT NULL,
    idPlato VARCHAR(10) NOT NULL
    );

CREATE TABLE carritosMenus (
    idCarrito VARCHAR(10) NOT NULL,
    idMenu VARCHAR2(10) NOT NULL
    );

CREATE TABLE pedidos (
    id VARCHAR2(10) NOT NULL,
    idConsumidor CHAR(10) NOT NULL,
    nombreConsumidor VARCHAR2(50) NOT NULL,
    direccionConsumidor VARCHAR2(50) NOT NULL,
    estado VARCHAR2(1) NOT NULL,
    idCarritoCompras VARCHAR(10) NOT NULL,
    idCalificacion VARCHAR(10) NOT NULL,
    idFactura VARCHAR(10) NOT NULL,
    idEnvio VARCHAR(10) NOT NULL,
    costo NUMBER(8) NOT NULL
    );

CREATE TABLE calificaciones_delizia (
    id VARCHAR2(10) NOT NULL,
    cantidadEstrellas NUMBER NOT NULL,
    comentario VARCHAR2(100) NOT NULL,
    idpedido VARCHAR2(10) NOT NULL
    );
    
CREATE TABLE facturas (
    id VARCHAR2(10) NOT NULL,
    idConsumidor CHAR(10) NOT NULL,
    fecha DATE NOT NULL,
    total NUMBER(8) NOT NULL,
    idBono VARCHAR2(10)
    );
    
CREATE TABLE envios (
    id VARCHAR2(10) NOT NULL,
    fecha DATE NOT NULL,
    fechaEntrega DATE NOT NULL,
    estado VARCHAR2(1) NOT NULL,
    nombreDomiciliario VARCHAR(50) NOT NULL,
    idDomiciliario VARCHAR2(10) NOT NULL,
    costo NUMBER(8) NOT NULL
    );
    
CREATE TABLE bonos_delizia (
    id VARCHAR2(10) NOT NULL,
    idConsumidor CHAR(10) NOT NULL,
    nitEmpresa CHAR(10) NOT NULL,
    estado VARCHAR2(11) NOT NULL,
    porcentajeDescuento NUMBER(8) NOT NULL,
    valor NUMBER(8) NOT NULL,
    fechaExpiracion DATE NOT NULL,
    idTipoBono VARCHAR2(10) 
    );
    
CREATE TABLE tiposBono (
    id VARCHAR2(10) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    nombreBono VARCHAR2(100) NOT NULL
    );

CREATE TABLE domiciliarios (
    id VARCHAR2(10) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR2(50) NOT NULL,
    duracion NUMBER NOT NULL,
    correo VARCHAR2(50) NOT NULL
    );

CREATE TABLE platos_empresas (
    idPlato VARCHAR(10) NOT NULL,
    nitEmpresa CHAR(10) NOT NULL,
    fechaCaducidad VARCHAR2(20) NOT NULL,
    unidadesDisponibles NUMBER NOT NULL,
    unidadesVendidas NUMBER NOT NULL
    );

CREATE TABLE Publicidad (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicidad XMLType
);
    